### ISSUE TITLE
Guideline to Add APIKey and APISecret for App is missing

### ISSUE THREAD

**Issue by mayankagwl** [LoginRadius/lr-cli#2]
There is no guideline for where to add APIkey and APISecret on the specific machine, it should be added in the Getting Started Section
![lrcli](https://user-images.githubusercontent.com/7309279/113294932-21776080-9315-11eb-8376-4ad66d2c47fd.png)

**Comment by mohammed786** [comment]
Hi @mayankagwl , Thanks for raising the issue.

As this CLI is meant for the LoginRadius Dashboard Users, we don't need to add any configuration for using this CLI. 

After installing the CLI, Once you run the command `lr login` and successfully authenticate. The `.lrcli` folder will be automatically created with all required information that is needed for further dashboard related actions.

You are facing the above issue because there was some bug in the login command, which will be fixed in the next release.
